name: Build LaTeX document
permissions: 
  contents: write
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: My_Resume.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: My_Resume.pdf
      - name: Commit data
        shell: bash
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          if ! git diff HEAD --exit-code > /dev/null 2>&1; then
            current_date=$(date +"%d-%m-%Y")
            git commit -m "Add new updated resume[$current_date]"
            git push origin main
          fi
